version: "3"
services: 
  web: 
    build: .
    container_name: p2p-wallet-system
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    command:
      yarn run debug
